{% set name = "google-cloud-life-sciences" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc6405ca63fc0e896e0a03a749fed1d208233339205db4dc7e9a378f740750fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.lifesciences
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-life-sciences
  summary: Python Client for Google Cloud Life Sciences
  doc_url: https://googleapis.dev/python/lifesciences/latest/index.html
  dev_url: https://github.com/googleapis/python-life-sciences
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
