{% set name = "google-cloud-life-sciences" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 159ac95c754ed478153cdf0b128266bc31b666cbd6b844092b4336d016adcea3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.lifesciences
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-life-sciences
  summary: Python Client for Google Cloud Life Sciences
  doc_url: https://googleapis.dev/python/lifesciences/latest/index.html
  dev_url: https://github.com/googleapis/python-life-sciences
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
