{% set name = "google-cloud-life-sciences" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d2aa9926e52ae72b3017805d6ed7acd1c4870366789d62b28d24b3d2532af64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.lifesciences
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-life-sciences
  summary: Python Client for Google Cloud Life Sciences
  doc_url: https://googleapis.dev/python/lifesciences/latest/index.html
  dev_url: https://github.com/googleapis/python-life-sciences
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
